server:
  port: 8765
spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
      routes:
        - id: Sem9hwMicroservice
          uri: http://localhost:8081/
          predicates:
            - Path=/notes/**
